# railway.toml
[build]
  command = "npm run build --prefix frontend"  # Command to build the frontend
  directory = "frontend/build"  # Directory where the built frontend files will be located

[deploy]
  command = "npm start --prefix backend"  # Command to start the backend server

[[builds]]
  name = "frontend"
  command = "npm run build --prefix frontend"  # Command to build the frontend
  directory = "frontend/build"  # Directory where the built frontend files will be located

[[builds]]
  name = "backend"
  command = "npm install --prefix backend && npm start --prefix backend"  # Command to install and start the backend
  directory = "backend"  # Directory for the backend

